/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sew9.worttrainer.flixlcookie;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

/*
 * @author Felix Warmuth 5CHIT
 * TestKlasse für die WortTrainer Aufgabe
 */
class AppTest {
    /*
     * Testet ob Laden funktioniert
     */
    @Test
    void LadenTest(){
        WortListe liste = new WortListe();
        WortTrainer trainer = new WortTrainer(liste);
        WortTrainerSpeichern sul = new WortTrainerSpeichern(trainer);
        sul.laden("Worttrainer.txt");
        assertEquals(5, trainer.getRichtig());
        assertEquals(2, trainer.getFalsch());
    }
    
    /*
     * Testet ob Speichern funktioniert
     */
    @Test
    void SpeichernTest(){
        WortListe liste = new WortListe();
        WortTrainer trainer = new WortTrainer(liste);
        WortTrainerSpeichern sul = new WortTrainerSpeichern(trainer);
        trainer.addRichtig(5);
        trainer.addFalsch(2);
        sul.speichern("WortTrainer.txt");
    }
    /*
     * Testet ob das Speichern und Laden funktioniert
     */
    @Test
    void SpeichernUndLadenTest(){
        WortListe liste = new WortListe();
        WortTrainer trainer = new WortTrainer(liste);
        WortTrainerSpeichern sul = new WortTrainerSpeichern(trainer);
        trainer.addRichtig(5);
        trainer.addFalsch(2);
        sul.speichern("WortTrainer.txt");
        sul.laden("WortTrainer.txt");
        assertEquals(5, trainer.getRichtig());
        assertEquals(2, trainer.getFalsch());
    }
}